# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: Hacker News

# Describe your segurity definitions here
securityDefinitions:
  apiKey:
    type: apiKey
    description: És la clau d'usuari generada per l'aplicació de Google.
    name: api_key
    in: header
produces:
  - application/json

# Describe your paths here
paths:

  # GET all coments
  /comments/:
    get:
      description: Retorna tots els comentaris
      responses:
        200:
          description: S'han retornat tots els comentaris.
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
        default:
          description: Error inesperat
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Crea un nou comentari
      responses:
        201:
          description: S'ha creat el comentari
          schema:
            $ref: '#/definitions/Comment'
        default:
          description: Error inesperat
          schema:
            $ref: '#/definitions/Error'
            
  # GET specific comment info
  /comments/:id:
    get:
      description: Retorna la informació d'un comentari
      responses:
        200:
          description: Comentari retornat
          schema:
            $ref: '#/definitions/Comment'
        404:
          description: Comentari no existeix
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Error inesperat
          schema:
            $ref: '#/definitions/Error'
            
  /comments/:id/vote:
    post:
      description: Vota el comentari amb id 'id'
      responses:
        200:
          description: S'ha votat el comentari amb l'usuari autenticat.
        404:
          description: Comentari no existeix
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Error inesperat
          schema:
            $ref: '#/definitions/Error'
            
  /users/:id/comments:
    get:
      description: Retorna tots els comentaris de l'usuari amb id 'id'
      responses:
        200:
          description: S'han retornat els comentaris de l'usuari
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
        404:
          description: L'usuari no existeix
          schema:
            $ref: '#/definitions/Error'
            
  # GET specific submission info
  /api/submissions/:id:
    get:
      description: Retorna la informació d'un publicació
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Submission'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  # GET specific reply info
  /api/replies/:id:
    get:
      description: Retorna la informació d'un resposta a un comentari
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Reply'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  # GET specific user info
  /api/users/:id:
    get:
      description: Retorna la informació d'un usuari
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # GET url submissions list
  /api/submissions:
    get:
      description: Retorna un llistat de publicacions de tipus 'URL', es a dir, amb el camp url no buit ordenat cronologicament.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Submission'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # GET ask submissions list
  /api/ask:
    get:
      description: Retorna un llistat de publicacions de tipus 'Ask', es a dir, amb el camp url buit ordenat cronologicament.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Submission'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # GET user threads list
  /api/threads/:id:
    get:
      description: Retorna el llistat de 'threads' que té un usuari.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Thread'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      
  # GET user list
  /api/users:
    get:
      description: Retorna un llistat de tots els usuaris.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
# Describe your definitons here
definitions:
  
  # Submission defition
  Submission:
    type: object
    properties:
      id:
        type: integer
        description: identificador unic de la publicació.
      title:
        type: string
        description: títol de la publicació.
      url:
        type: string
        description: url associada a la publicació.
      text:
        type: string
        description: text associat a la publicació.
      user_id:
        type: integer
        description: identificador de l'usuari creador de la publicació.
      created_at:
        type: string
        description: instant de creació de la publicació.
      updated_at:
        type: string
        description: instant de l'última actualització de la publicació.
  
  # Comment defintion
  Comment:
    type: object
    properties:
      id:
        type: integer
        description: identificador unic del comentari.
      content:
        type: string
        description: contingut associat del comentari.
      user_id:
        type: integer
        description: identificador de l'usuari creador del comentari.
      submission_id:
        type: integer
        description: identificador de la publicació relacionada.
      created_at:
        type: string
        description: instant de creació del comentari.
      updated_at:
        type: string
        description: instant de l'última actualització del comentari.

  # Reply definition
  Reply:
    type: object
    properties:
      id:
        type: integer
        description: identificador unic de la resposta.
      content:
        type: string
        description: contingut associat de la resposta.
      user_id:
        type: integer
        description: identificador de l'usuari creador de la resposta.
      comment_id:
        type: integer
        description: identificador del comentari relacionat.
      created_at:
        type: string
        description: instant de creació de la resposta.
      updated_at:
        type: string
        description: instant de l'última actualització de la resposta.
        
  # Thread definition
  Thread:
    type: object
    properties:
      comments:
        type: array
        description: llistat de comentaris de l'usuari.
        items:
          $ref: "#/definitions/Comment"
      replies:
        type: array
        description: llistat de respostes de l'usuari.
        items:
          $ref: "#/definitions/Reply"

  # User definition
  User:
    type: object
    properties:
      id:
        type: integer
        description: identificador unic de l'usuari.
      name:
        type: string
        description: nom de l'usuari.
      about:
        type: string
        description: descripció de l'usuari.
      email:
        type: string
        description: correu de l'usuari.
      password:
        type: string
        description: contrasenya de l'usuari.
      created_at:
        type: string
        description: instant de creació de l'usuari.
      updated_at:
        type: string
        description: instant de l'última actualització de l'usuari.
  
  # Error defintion
  Error:
    type: object
    properties:
        code:
          type: integer
          description: codi de l'error.
          format: int32
        message:
          type: string
          description: missatge de l'error.
        fields:
          type: string
          description: camps de l'error.